# The Deployment resource manages a group of identical pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world  
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: hello-world  
  template:
    metadata:
      labels:
        app: hello-world 
    spec:
      containers:
      - name: hello-world  
        image: troz271/hello-world-app:latest 
        ports:
        - containerPort: 80  # The port the container exposes.
---
# The Service resource to expose the application to the outside world.
apiVersion: v1
kind: Service
metadata:
  name: hello-world  
spec:
  selector:
    app: hello-world  
  ports:
  - protocol: TCP  # The protocol used by the service.
    port: 80  # The port that will be exposed.
    targetPort: 80  # The port on the container that the service should forward to.
  type: LoadBalancer  
